# This config file for Travis CI utilizes https://github.com/ros-planning/moveit_ci/ package.
sudo: required
dist: trusty
services:
  - docker
language: generic
compiler:
  - gcc
notifications:
  email:
    recipients:
      - henningkayser@picknik.ai
env:
  matrix:
    - ROS_DISTRO=kinetic  ROS_REPO=ros-shadow-fixed UPSTREAM_WORKSPACE=./rtr_moveit.rosinstall
script:
  - source .travis/travis.sh
addons:
  # https://docs.travis-ci.com/user/ssh-known-hosts/
  ssh_known_hosts:
    - bitbucket.org
